export const bokaApi = 'https://laravel.boka.cn/api'

export const ERR_NUM = 0

export const token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xhcmF2ZWwuYm9rYS5jbi9hcGkvc2NhbmxvZ2luLzE1Mzk4MzQzMzAiLCJpYXQiOjE1Mzk4MzQzMzYsImV4cCI6MTU0MDY5ODMzNiwibmJmIjoxNTM5ODM0MzM2LCJqdGkiOiJxVW5mb3FpVUpNeDRncUVKIiwic3ViIjo1MzYsInBydiI6Ijg2NjVhZTk3NzVjZjI2ZjZiOGU0OTZmODZmYTUzNmQ2OGRkNzE4MTgifQ.l96twbdGBcwr7FTC2egiXz5PwDEuRN1h4mNv5vOUCwE'
